name: prerelease-pr

permissions:
  contents: read
  id-token: write

on:
  pull_request:

jobs:
  publish:
    if: github.repository_owner == 'nuxt-modules'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: "https://registry.npmjs.org"
      - name: "Deprecate previous PR prerelease"
        run: |
          PACKAGE_NAME=$(jq -r ".name" package.json)
          TAG="pr-${{ github.event.number }}"
          PREVIOUS_VERSION=$(npm view "$PACKAGE_NAME" dist-tags."$TAG" 2>/dev/null)
          if [ -n "$PREVIOUS_VERSION" ]; then
            npm deprecate "$PACKAGE_NAME@$PREVIOUS_VERSION" "Replaced by newer prerelease version"
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: npm ci
      - name: "Generate new version"
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          CURRENT_VERSION=$(jq -r '.version' package.json)
          VERSION="${CURRENT_VERSION}-pr.${{ github.event.number }}.${SHORT_SHA}"
          npm version $VERSION --no-git-tag-version
      - run: npm publish --provenance --tag pr-${{ github.event.number }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
